raw_data_remote: /data/lexa/20221017_1538_MN34986_FAV36531_9a1db0d5/fast5_pass
raw_data_local: data
outputs_local: results
meganizer: /usr/local/share/megan/tools/daa-meganizer
megan_map: /opt/megan-map-Jan2021.db
